# Generated by Django 2.2.5 on 2019-11-24 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_publish'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-time',)},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-publish',)},
        ),
        migrations.RemoveField(
            model_name='postview',
            name='user',
        ),
    ]
